//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CometUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CometUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CometUI_Title_Error {
            get {
                return ResourceManager.GetString("CometUI_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string InputFilesControl_AddInputFiles_Error {
            get {
                return ResourceManager.GetString("InputFilesControl_AddInputFiles_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Input File.
        /// </summary>
        internal static string InputFilesControl_ShowAddInputFile_Open_Input_File {
            get {
                return ResourceManager.GetString("InputFilesControl_ShowAddInputFile_Open_Input_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Proteome Database File.
        /// </summary>
        internal static string InputFilesControl_ShowOpenDatabaseFile_Open_Proteome_Database_File {
            get {
                return ResourceManager.GetString("InputFilesControl_ShowOpenDatabaseFile_Open_Proteome_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Search Completed.
        /// </summary>
        internal static string RunSearchBackgroundWorker_RunSearchBackgroundWorkerRunWorkerCompleted_Run_Search_Completed {
            get {
                return ResourceManager.GetString("RunSearchBackgroundWorker_RunSearchBackgroundWorkerRunWorkerCompleted_Run_Search_" +
                        "Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Completed.
        /// </summary>
        internal static string RunSearchDlg_BtnRunSearchClick_Search_Completed {
            get {
                return ResourceManager.GetString("RunSearchDlg_BtnRunSearchClick_Search_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Failed.
        /// </summary>
        internal static string RunSearchDlg_BtnRunSearchClick_Search_Failed {
            get {
                return ResourceManager.GetString("RunSearchDlg_BtnRunSearchClick_Search_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mass Diff.
        /// </summary>
        internal static string StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Invalid_Mass_Diff {
            get {
                return ResourceManager.GetString("StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Invalid_Mass_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number for the mass difference..
        /// </summary>
        internal static string StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Please_enter_a_valid_number_for_the_mass_difference_ {
            get {
                return ResourceManager.GetString("StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Please_enter_a_valid_n" +
                        "umber_for_the_mass_difference_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mass Diff.
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Mass_Diff {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Mass_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Max Mods.
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Max_Mods {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Max_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Residue.
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Residue {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Residue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number between 0 and 64..
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_between_0_and_64_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_" +
                        "between_0_and_64_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number for the mass difference..
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_for_the_mass_difference_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_" +
                        "for_the_mass_difference_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid residue..
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_residue_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_residue" +
                        "_", resourceCulture);
            }
        }
    }
}
