//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CometUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CometUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comet UI provides a graphical user interface to run Comet searches, set and save search parameters, and import and export the parameters..
        /// </summary>
        internal static string AboutDlg_SetAboutText_Comet_UI_provides_a_graphical_user_interface_to_run_Comet_searches__set_and_save_search_parameters__and_import_and_export_the_parameters_ {
            get {
                return ResourceManager.GetString("AboutDlg_SetAboutText_Comet_UI_provides_a_graphical_user_interface_to_run_Comet_s" +
                        "earches__set_and_save_search_parameters__and_import_and_export_the_parameters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comet {
            get {
                object obj = ResourceManager.GetObject("comet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings Changed.
        /// </summary>
        internal static string CometUI_CometUIFormClosing_Search_Settings_Changed {
            get {
                return ResourceManager.GetString("CometUI_CometUIFormClosing_Search_Settings_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Results Settings Changed.
        /// </summary>
        internal static string CometUI_CometUIFormClosing_View_Results_Settings_Changed {
            get {
                return ResourceManager.GetString("CometUI_CometUIFormClosing_View_Results_Settings_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have modified the search settings. Would you like to save the changes before you exit?.
        /// </summary>
        internal static string CometUI_CometUIFormClosing_You_have_modified_the_search_settings__Would_you_like_to_save_the_changes_before_you_exit_ {
            get {
                return ResourceManager.GetString("CometUI_CometUIFormClosing_You_have_modified_the_search_settings__Would_you_like_" +
                        "to_save_the_changes_before_you_exit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have modified the view results settings. Would you like to save the changes before you exit?.
        /// </summary>
        internal static string CometUI_CometUIFormClosing_You_have_modified_the_view_results_settings__Would_you_like_to_save_the_changes_before_you_exit_ {
            get {
                return ResourceManager.GetString("CometUI_CometUIFormClosing_You_have_modified_the_view_results_settings__Would_you" +
                        "_like_to_save_the_changes_before_you_exit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite the current settings?.
        /// </summary>
        internal static string CometUI_SaveSearchSettingsToolStripMenuItemClick_Are_you_sure_you_want_to_overwrite_the_current_settings_ {
            get {
                return ResourceManager.GetString("CometUI_SaveSearchSettingsToolStripMenuItemClick_Are_you_sure_you_want_to_overwri" +
                        "te_the_current_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Search Settings.
        /// </summary>
        internal static string CometUI_SaveSearchSettingsToolStripMenuItemClick_Save_Search_Settings {
            get {
                return ResourceManager.GetString("CometUI_SaveSearchSettingsToolStripMenuItemClick_Save_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PepXML File.
        /// </summary>
        internal static string CometUI_ShowOpenPepXMLFile_Open_PepXML_File {
            get {
                return ResourceManager.GetString("CometUI_ShowOpenPepXMLFile_Open_PepXML_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CometUI_Title_Error {
            get {
                return ResourceManager.GetString("CometUI_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite the current settings?.
        /// </summary>
        internal static string CometUI_ViewResultsSettingsToolStripMenuItemClick_Are_you_sure_you_want_to_overwrite_the_current_settings_ {
            get {
                return ResourceManager.GetString("CometUI_ViewResultsSettingsToolStripMenuItemClick_Are_you_sure_you_want_to_overwr" +
                        "ite_the_current_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save View Results Settings.
        /// </summary>
        internal static string CometUI_ViewResultsSettingsToolStripMenuItemClick_Save_View_Results_Settings {
            get {
                return ResourceManager.GetString("CometUI_ViewResultsSettingsToolStripMenuItemClick_Save_View_Results_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  already exists in this folder. Would you like to replace it?.
        /// </summary>
        internal static string ExportParamsDlg_BtnExportClick__already_exists_in_this_folder__Would_you_like_to_replace_it_ {
            get {
                return ResourceManager.GetString("ExportParamsDlg_BtnExportClick__already_exists_in_this_folder__Would_you_like_to_" +
                        "replace_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ExportParamsDlg_BtnExportClick_Error {
            get {
                return ResourceManager.GetString("ExportParamsDlg_BtnExportClick_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Failed.
        /// </summary>
        internal static string ExportParamsDlg_BtnExportClick_Export_Failed {
            get {
                return ResourceManager.GetString("ExportParamsDlg_BtnExportClick_Export_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Search Settings.
        /// </summary>
        internal static string ExportParamsDlg_BtnExportClick_Export_Search_Settings {
            get {
                return ResourceManager.GetString("ExportParamsDlg_BtnExportClick_Export_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name has Invalid Characters.
        /// </summary>
        internal static string ExportParamsDlg_BtnExportClick_File_Name_has_Invalid_Characters {
            get {
                return ResourceManager.GetString("ExportParamsDlg_BtnExportClick_File_Name_has_Invalid_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name has invalid characters..
        /// </summary>
        internal static string ExportParamsDlg_BtnExportClick_File_name_has_invalid_characters_ {
            get {
                return ResourceManager.GetString("ExportParamsDlg_BtnExportClick_File_name_has_invalid_characters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        internal static string ExportParamsDlg_BtnExportClick_Save_Failed {
            get {
                return ResourceManager.GetString("ExportParamsDlg_BtnExportClick_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings exported to .
        /// </summary>
        internal static string ExportParamsDlg_BtnExportClick_Settings_exported_to_ {
            get {
                return ResourceManager.GetString("ExportParamsDlg_BtnExportClick_Settings_exported_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the Comet version. Settings cannot be exported without a valid Comet version..
        /// </summary>
        internal static string ExportParamsDlg_BtnExportClick_Unable_to_get_the_Comet_version__Settings_cannot_be_exported_without_a_valid_Comet_version {
            get {
                return ResourceManager.GetString("ExportParamsDlg_BtnExportClick_Unable_to_get_the_Comet_version__Settings_cannot_b" +
                        "e_exported_without_a_valid_Comet_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not specified a proteome database name in the Input Settings. The params file you are about to create will leave the &apos;database_name&apos; field blank. Click Ok to continue with no &quot;database_name&quot;, or Cancel to abort..
        /// </summary>
        internal static string ExportParamsDlg_BtnExportClick_You_have_not_specified_a_proteome_database_name_in_the_Input_Settings_The_params_file_you_are_about_to_create_will_leave_the_database_name_field_blank {
            get {
                return ResourceManager.GetString("ExportParamsDlg_BtnExportClick_You_have_not_specified_a_proteome_database_name_in" +
                        "_the_Input_Settings_The_params_file_you_are_about_to_create_will_leave_the_datab" +
                        "ase_name_field_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate the params file. .
        /// </summary>
        internal static string ExportParamsDlg_ExportCometParams_Failed_to_generate_the_params_file_ {
            get {
                return ResourceManager.GetString("ExportParamsDlg_ExportCometParams_Failed_to_generate_the_params_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comet.
        /// </summary>
        internal static string ExportParamsDlg_ExportParamsDlg_comet {
            get {
                return ResourceManager.GetString("ExportParamsDlg_ExportParamsDlg_comet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comet.params.
        /// </summary>
        internal static string ExportParamsDlg_ExportParamsDlg_comet_params {
            get {
                return ResourceManager.GetString("ExportParamsDlg_ExportParamsDlg_comet_params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comet Params Files (*.params)|*.params.
        /// </summary>
        internal static string ImportParamsDlg_BtnBrowseProteomeDbFileClick_Comet_Params_Files____params____params {
            get {
                return ResourceManager.GetString("ImportParamsDlg_BtnBrowseProteomeDbFileClick_Comet_Params_Files____params____para" +
                        "ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Params File.
        /// </summary>
        internal static string ImportParamsDlg_BtnBrowseProteomeDbFileClick_Open_Params_File {
            get {
                return ResourceManager.GetString("ImportParamsDlg_BtnBrowseProteomeDbFileClick_Open_Params_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import completed successfully..
        /// </summary>
        internal static string ImportParamsDlg_BtnImportClick_Import_completed_successfully_ {
            get {
                return ResourceManager.GetString("ImportParamsDlg_BtnImportClick_Import_completed_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed. .
        /// </summary>
        internal static string ImportParamsDlg_BtnImportClick_Import_failed_ {
            get {
                return ResourceManager.GetString("ImportParamsDlg_BtnImportClick_Import_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Search Settings.
        /// </summary>
        internal static string ImportParamsDlg_BtnImportClick_Import_Search_Settings {
            get {
                return ResourceManager.GetString("ImportParamsDlg_BtnImportClick_Import_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string InputFilesControl_AddInputFiles_Error {
            get {
                return ResourceManager.GetString("InputFilesControl_AddInputFiles_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Input File.
        /// </summary>
        internal static string InputFilesControl_ShowAddInputFile_Open_Input_File {
            get {
                return ResourceManager.GetString("InputFilesControl_ShowAddInputFile_Open_Input_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Proteome Database File.
        /// </summary>
        internal static string InputFilesControl_ShowOpenDatabaseFile_Open_Proteome_Database_File {
            get {
                return ResourceManager.GetString("InputFilesControl_ShowOpenDatabaseFile_Open_Proteome_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string InputSettingsControl_VerifyAndSaveSettings_Search_Settings {
            get {
                return ResourceManager.GetString("InputSettingsControl_VerifyAndSaveSettings_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string OutputSettingsControl_VerifyAndUpdateSettings_Search_Settings {
            get {
                return ResourceManager.GetString("OutputSettingsControl_VerifyAndUpdateSettings_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation request has been sent, but the background proces may continue running until the request has been processed..
        /// </summary>
        internal static string ProgressDlg_ProgressDlgClosing_Cancellation_request_has_been_sent__but_the_background_proces_may_continue_running_until_the_request_has_been_processed_ {
            get {
                return ResourceManager.GetString("ProgressDlg_ProgressDlgClosing_Cancellation_request_has_been_sent__but_the_backgr" +
                        "ound_proces_may_continue_running_until_the_request_has_been_processed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the operation?.
        /// </summary>
        internal static string ProgressDlg_VerifyCancel_Are_you_sure_you_want_to_cancel_the_operation_ {
            get {
                return ResourceManager.GetString("ProgressDlg_VerifyCancel_Are_you_sure_you_want_to_cancel_the_operation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation request sent, but the background proces may continue running for a while. If you want to continue to receive progress status, please click Cancel. Otherwise, click OK.
        /// </summary>
        internal static string ProgressDlg_VerifyCancel_Cancellation_request_sent__but_the_background_proces_may_continue_running_for_a_while__If_you_want_to_continue_to_receive_progress_status__please_click_Cancel__Otherwise__click_OK {
            get {
                return ResourceManager.GetString("ProgressDlg_VerifyCancel_Cancellation_request_sent__but_the_background_proces_may" +
                        "_continue_running_for_a_while__If_you_want_to_continue_to_receive_progress_statu" +
                        "s__please_click_Cancel__Otherwise__click_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation request will be sent, but the background proces may continue running until the request has been processed. Click Cancel to continue receiving progress status. Otherwise, please click OK..
        /// </summary>
        internal static string ProgressDlg_VerifyCancel_Cancellation_request_will_be_sent__but_the_background_proces_may_continue_running_until_the_request_has_been_processed__Click_Cancel_to_continue_receiving_progress_status__Otherwise__please_click_OK_ {
            get {
                return ResourceManager.GetString("ProgressDlg_VerifyCancel_Cancellation_request_will_be_sent__but_the_background_pr" +
                        "oces_may_continue_running_until_the_request_has_been_processed__Click_Cancel_to_" +
                        "continue_receiving_progress_status__Otherwise__please_click_OK_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Search.
        /// </summary>
        internal static string RunSearchBackgroundWorker_RunSearchBackgroundWorkerRunWorkerCompleted_Run_Search {
            get {
                return ResourceManager.GetString("RunSearchBackgroundWorker_RunSearchBackgroundWorkerRunWorkerCompleted_Run_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Search Completed.
        /// </summary>
        internal static string RunSearchBackgroundWorker_RunSearchBackgroundWorkerRunWorkerCompleted_Run_Search_Completed {
            get {
                return ResourceManager.GetString("RunSearchBackgroundWorker_RunSearchBackgroundWorkerRunWorkerCompleted_Run_Search_" +
                        "Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Completed.
        /// </summary>
        internal static string RunSearchDlg_BtnRunSearchClick_Search_Completed {
            get {
                return ResourceManager.GetString("RunSearchDlg_BtnRunSearchClick_Search_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Failed.
        /// </summary>
        internal static string RunSearchDlg_BtnRunSearchClick_Search_Failed {
            get {
                return ResourceManager.GetString("RunSearchDlg_BtnRunSearchClick_Search_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Search.
        /// </summary>
        internal static string RunSearchDlg_ProteomeDbFileNameChanged_Run_Search {
            get {
                return ResourceManager.GetString("RunSearchDlg_ProteomeDbFileNameChanged_Run_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update the proteome database file name in the search settings with the one you have specified here?.
        /// </summary>
        internal static string RunSearchDlg_ProteomeDbFileNameChanged_Would_you_like_to_update_the_proteome_database_file_name_in_the_search_settings_with_the_one_you_have_specified_here_ {
            get {
                return ResourceManager.GetString("RunSearchDlg_ProteomeDbFileNameChanged_Would_you_like_to_update_the_proteome_data" +
                        "base_file_name_in_the_search_settings_with_the_one_you_have_specified_here_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel search?.
        /// </summary>
        internal static string RunSearchProgressDlg_VerifyCancel_Are_you_sure_you_want_to_cancel_search_ {
            get {
                return ResourceManager.GetString("RunSearchProgressDlg_VerifyCancel_Are_you_sure_you_want_to_cancel_search_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update all search settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Could_not_update_all_search_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Could_not_update_all_search_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating enzyme settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_enzyme_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_enzyme_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating Input settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_input_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_input_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating mass settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_mass_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_mass_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating misc settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_misc_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_misc_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating Output settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_Output_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_Output_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating static mods settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_static_mods_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_static_mods_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating var mods settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_var_mods_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_var_mods_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Search_Settings {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update input settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Unable_to_update_input_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Unable_to_update_input_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the input settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Unable_to_update_the_input_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Unable_to_update_the_input_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string SearchSettingsDlg_Search_Settings {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mass Diff.
        /// </summary>
        internal static string StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Invalid_Mass_Diff {
            get {
                return ResourceManager.GetString("StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Invalid_Mass_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number for the mass difference..
        /// </summary>
        internal static string StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Please_enter_a_valid_number_for_the_mass_difference_ {
            get {
                return ResourceManager.GetString("StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Please_enter_a_valid_n" +
                        "umber_for_the_mass_difference_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Variable Mod.
        /// </summary>
        internal static string VarModSettingsControl_AddVarModBtnClick_Add_Variable_Mod {
            get {
                return ResourceManager.GetString("VarModSettingsControl_AddVarModBtnClick_Add_Variable_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of variable mods allowed..
        /// </summary>
        internal static string VarModSettingsControl_AddVarModBtnClick_You_have_reached_the_maximum_number_of_variable_mods_allowed_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_AddVarModBtnClick_You_have_reached_the_maximum_number_of_va" +
                        "riable_mods_allowed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Terminus Distance.
        /// </summary>
        internal static string VarModSettingsControl_ValidateTermDistCellEdit_Invalid_Terminus_Distance {
            get {
                return ResourceManager.GetString("VarModSettingsControl_ValidateTermDistCellEdit_Invalid_Terminus_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a decimal number..
        /// </summary>
        internal static string VarModSettingsControl_ValidateTermDistCellEdit_Please_enter_a_decimal_number_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_ValidateTermDistCellEdit_Please_enter_a_decimal_number_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mass Diff.
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Mass_Diff {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Mass_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Max Mods.
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Max_Mods {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Max_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Residue.
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Residue {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Residue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number between 0 and 64..
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_between_0_and_64_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_" +
                        "between_0_and_64_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number for the mass difference..
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_for_the_mass_difference_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_" +
                        "for_the_mass_difference_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid residue..
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_residue_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_residue" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Results.
        /// </summary>
        internal static string ViewResults_View_Results_Title {
            get {
                return ResourceManager.GetString("ViewResults_View_Results_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the results pep.xml file. .
        /// </summary>
        internal static string ViewResultsSummaryOptionsControl_UpdateSearchSummaryLabel_Could_not_read_the_results_pep_xml_file__ {
            get {
                return ResourceManager.GetString("ViewResultsSummaryOptionsControl_UpdateSearchSummaryLabel_Could_not_read_the_resu" +
                        "lts_pep_xml_file__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string ViewSearchResultsControl_HideViewOptionsPanel__ {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_HideViewOptionsPanel__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show options.
        /// </summary>
        internal static string ViewSearchResultsControl_HideViewOptionsPanel_Show_options {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_HideViewOptionsPanel_Show_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Protein Database File.
        /// </summary>
        internal static string ViewSearchResultsControl_Open_Protein_Database_File_Dlg_Title {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_Open_Protein_Database_File_Dlg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the protein database file. .
        /// </summary>
        internal static string ViewSearchResultsControl_ShowProteinSequence_Could_not_find_the_protein_database_file__ {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_ShowProteinSequence_Could_not_find_the_protein_database_" +
                        "file__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database: .
        /// </summary>
        internal static string ViewSearchResultsControl_ShowProteinSequence_Database__ {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_ShowProteinSequence_Database__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Results Error.
        /// </summary>
        internal static string ViewSearchResultsControl_ShowProteinSequence_View_Results_Error {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_ShowProteinSequence_View_Results_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to specify an alternate path to the file?.
        /// </summary>
        internal static string ViewSearchResultsControl_ShowProteinSequence_Would_you_like_to_specify_an_alternate_path_to_the_file_ {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_ShowProteinSequence_Would_you_like_to_specify_an_alterna" +
                        "te_path_to_the_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string ViewSearchResultsControl_ShowViewOptionsPanel__ {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_ShowViewOptionsPanel__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide options.
        /// </summary>
        internal static string ViewSearchResultsControl_ShowViewOptionsPanel_Hide_options {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_ShowViewOptionsPanel_Hide_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the results pep.xml file. .
        /// </summary>
        internal static string ViewSearchResultsControl_UpdateSearchResultsList_Could_not_read_the_results_pep_xml_file__ {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_UpdateSearchResultsList_Could_not_read_the_results_pep_x" +
                        "ml_file__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the spectra file. Would you like to try specifying an alternate path to the file?.
        /// </summary>
        internal static string ViewSearchResultsControl_ViewSpectra_Could_not_read_the_spectra_file__Would_you_like_to_try_specifying_an_alternate_path_to_the_file_ {
            get {
                return ResourceManager.GetString("ViewSearchResultsControl_ViewSpectra_Could_not_read_the_spectra_file__Would_you_l" +
                        "ike_to_try_specifying_an_alternate_path_to_the_file_", resourceCulture);
            }
        }
    }
}
