//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CometUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CometUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CometUI_Title_Error {
            get {
                return ResourceManager.GetString("CometUI_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string InputFilesControl_AddInputFiles_Error {
            get {
                return ResourceManager.GetString("InputFilesControl_AddInputFiles_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Input File.
        /// </summary>
        internal static string InputFilesControl_ShowAddInputFile_Open_Input_File {
            get {
                return ResourceManager.GetString("InputFilesControl_ShowAddInputFile_Open_Input_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Proteome Database File.
        /// </summary>
        internal static string InputFilesControl_ShowOpenDatabaseFile_Open_Proteome_Database_File {
            get {
                return ResourceManager.GetString("InputFilesControl_ShowOpenDatabaseFile_Open_Proteome_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string InputSettingsControl_VerifyAndSaveSettings_Search_Settings {
            get {
                return ResourceManager.GetString("InputSettingsControl_VerifyAndSaveSettings_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string OutputSettingsControl_VerifyAndUpdateSettings_Search_Settings {
            get {
                return ResourceManager.GetString("OutputSettingsControl_VerifyAndUpdateSettings_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation request sent, but the background proces may continue running for a while. If you want to continue to receive progress status, please click Cancel. Otherwise, click OK.
        /// </summary>
        internal static string ProgressDlg_VerifyCancel_Cancellation_request_sent__but_the_background_proces_may_continue_running_for_a_while__If_you_want_to_continue_to_receive_progress_status__please_click_Cancel__Otherwise__click_OK {
            get {
                return ResourceManager.GetString("ProgressDlg_VerifyCancel_Cancellation_request_sent__but_the_background_proces_may" +
                        "_continue_running_for_a_while__If_you_want_to_continue_to_receive_progress_statu" +
                        "s__please_click_Cancel__Otherwise__click_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Search Completed.
        /// </summary>
        internal static string RunSearchBackgroundWorker_RunSearchBackgroundWorkerRunWorkerCompleted_Run_Search_Completed {
            get {
                return ResourceManager.GetString("RunSearchBackgroundWorker_RunSearchBackgroundWorkerRunWorkerCompleted_Run_Search_" +
                        "Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Completed.
        /// </summary>
        internal static string RunSearchDlg_BtnRunSearchClick_Search_Completed {
            get {
                return ResourceManager.GetString("RunSearchDlg_BtnRunSearchClick_Search_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Failed.
        /// </summary>
        internal static string RunSearchDlg_BtnRunSearchClick_Search_Failed {
            get {
                return ResourceManager.GetString("RunSearchDlg_BtnRunSearchClick_Search_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Search.
        /// </summary>
        internal static string RunSearchDlg_ProteomeDbFileNameChanged_Run_Search {
            get {
                return ResourceManager.GetString("RunSearchDlg_ProteomeDbFileNameChanged_Run_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update the proteome database file name in the search settings with the one you have specified here?.
        /// </summary>
        internal static string RunSearchDlg_ProteomeDbFileNameChanged_Would_you_like_to_update_the_proteome_database_file_name_in_the_search_settings_with_the_one_you_have_specified_here_ {
            get {
                return ResourceManager.GetString("RunSearchDlg_ProteomeDbFileNameChanged_Would_you_like_to_update_the_proteome_data" +
                        "base_file_name_in_the_search_settings_with_the_one_you_have_specified_here_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update all search settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Could_not_update_all_search_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Could_not_update_all_search_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating enzyme settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_enzyme_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_enzyme_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating Input settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_input_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_input_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating mass settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_mass_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_mass_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating Output settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Error_updating_Output_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Error_updating_Output_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Search_Settings {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update input settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Unable_to_update_input_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Unable_to_update_input_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the input settings..
        /// </summary>
        internal static string SearchSettingsDlg_BtnOKClick_Unable_to_update_the_input_settings_ {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_BtnOKClick_Unable_to_update_the_input_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Settings.
        /// </summary>
        internal static string SearchSettingsDlg_Search_Settings {
            get {
                return ResourceManager.GetString("SearchSettingsDlg_Search_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mass Diff.
        /// </summary>
        internal static string StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Invalid_Mass_Diff {
            get {
                return ResourceManager.GetString("StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Invalid_Mass_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number for the mass difference..
        /// </summary>
        internal static string StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Please_enter_a_valid_number_for_the_mass_difference_ {
            get {
                return ResourceManager.GetString("StaticModSettingsControl_StaticModsDataGridViewCellEndEdit_Please_enter_a_valid_n" +
                        "umber_for_the_mass_difference_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mass Diff.
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Mass_Diff {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Mass_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Max Mods.
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Max_Mods {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Max_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Residue.
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Residue {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Invalid_Residue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number between 0 and 64..
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_between_0_and_64_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_" +
                        "between_0_and_64_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number for the mass difference..
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_for_the_mass_difference_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_number_" +
                        "for_the_mass_difference_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid residue..
        /// </summary>
        internal static string VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_residue_ {
            get {
                return ResourceManager.GetString("VarModSettingsControl_VarModsDataGridViewCellEndEdit_Please_enter_a_valid_residue" +
                        "_", resourceCulture);
            }
        }
    }
}
