//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CometUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProteomeDatabaseFile {
            get {
                return ((string)(this["ProteomeDatabaseFile"]));
            }
            set {
                this["ProteomeDatabaseFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NucleotideReadingFrame {
            get {
                return ((int)(this["NucleotideReadingFrame"]));
            }
            set {
                this["NucleotideReadingFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsProteinDB {
            get {
                return ((bool)(this["IsProteinDB"]));
            }
            set {
                this["IsProteinDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SearchType {
            get {
                return ((int)(this["SearchType"]));
            }
            set {
                this["SearchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DECOY_")]
        public string DecoyPrefix {
            get {
                return ((string)(this["DecoyPrefix"]));
            }
            set {
                this["DecoyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fully-digested")]
        public string EnzymeTermini {
            get {
                return ((string)(this["EnzymeTermini"]));
            }
            set {
                this["EnzymeTermini"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AllowedMissedCleavages {
            get {
                return ((int)(this["AllowedMissedCleavages"]));
            }
            set {
                this["AllowedMissedCleavages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0,No_enzyme,0,-,-</string>
  <string>1,Trypsin,1,KR,P</string>
  <string>2,Trypsin/P,1,KR,-</string>
  <string>3,Lys_C,1,K,P</string>
  <string>4,Lys_N,0,K,-</string>
  <string>5,Arg_C,1,R,P</string>
  <string>6,Asp_N,0,D,-</string>
  <string>7,CNBr,1,M,-</string>
  <string>8,Glu_C,1,DE,P</string>
  <string>9,PepsinA,1,FL,P</string>
  <string>10,Chymotrypsin,1,FWYL,P</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EnzymeInfo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EnzymeInfo"]));
            }
            set {
                this["EnzymeInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SearchEnzymeNumber {
            get {
                return ((int)(this["SearchEnzymeNumber"]));
            }
            set {
                this["SearchEnzymeNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SampleEnzymeNumber {
            get {
                return ((int)(this["SampleEnzymeNumber"]));
            }
            set {
                this["SampleEnzymeNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double PrecursorMassTolerance {
            get {
                return ((double)(this["PrecursorMassTolerance"]));
            }
            set {
                this["PrecursorMassTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("amu")]
        public string PrecursorMassUnit {
            get {
                return ((string)(this["PrecursorMassUnit"]));
            }
            set {
                this["PrecursorMassUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MH+")]
        public string PrecursorToleranceType {
            get {
                return ((string)(this["PrecursorToleranceType"]));
            }
            set {
                this["PrecursorToleranceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mono")]
        public string PrecursorMassType {
            get {
                return ((string)(this["PrecursorMassType"]));
            }
            set {
                this["PrecursorMassType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no C13")]
        public string PrecursorIsotopeError {
            get {
                return ((string)(this["PrecursorIsotopeError"]));
            }
            set {
                this["PrecursorIsotopeError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0005")]
        public double FragmentBinSize {
            get {
                return ((double)(this["FragmentBinSize"]));
            }
            set {
                this["FragmentBinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.04")]
        public double FragmentBinOffset {
            get {
                return ((double)(this["FragmentBinOffset"]));
            }
            set {
                this["FragmentBinOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mono")]
        public string FragmentMassType {
            get {
                return ((string)(this["FragmentMassType"]));
            }
            set {
                this["FragmentMassType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAIons {
            get {
                return ((bool)(this["UseAIons"]));
            }
            set {
                this["UseAIons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseBIons {
            get {
                return ((bool)(this["UseBIons"]));
            }
            set {
                this["UseBIons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCIons {
            get {
                return ((bool)(this["UseCIons"]));
            }
            set {
                this["UseCIons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseXIons {
            get {
                return ((bool)(this["UseXIons"]));
            }
            set {
                this["UseXIons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseYIons {
            get {
                return ((bool)(this["UseYIons"]));
            }
            set {
                this["UseYIons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseZIons {
            get {
                return ((bool)(this["UseZIons"]));
            }
            set {
                this["UseZIons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseNLIons {
            get {
                return ((bool)(this["UseNLIons"]));
            }
            set {
                this["UseNLIons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheoreticalFragmentIons {
            get {
                return ((bool)(this["TheoreticalFragmentIons"]));
            }
            set {
                this["TheoreticalFragmentIons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutputFormatPepXML {
            get {
                return ((bool)(this["OutputFormatPepXML"]));
            }
            set {
                this["OutputFormatPepXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputFormatPinXML {
            get {
                return ((bool)(this["OutputFormatPinXML"]));
            }
            set {
                this["OutputFormatPinXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputFormatOutFiles {
            get {
                return ((bool)(this["OutputFormatOutFiles"]));
            }
            set {
                this["OutputFormatOutFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputFormatSqtFile {
            get {
                return ((bool)(this["OutputFormatSqtFile"]));
            }
            set {
                this["OutputFormatSqtFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintExpectScoreInPlaceOfSP {
            get {
                return ((bool)(this["PrintExpectScoreInPlaceOfSP"]));
            }
            set {
                this["PrintExpectScoreInPlaceOfSP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int NumOutputLines {
            get {
                return ((int)(this["NumOutputLines"]));
            }
            set {
                this["NumOutputLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputFormatTextFile {
            get {
                return ((bool)(this["OutputFormatTextFile"]));
            }
            set {
                this["OutputFormatTextFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputFormatShowFragmentIons {
            get {
                return ((bool)(this["OutputFormatShowFragmentIons"]));
            }
            set {
                this["OutputFormatShowFragmentIons"] = value;
            }
        }
    }
}
