//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CometUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class RunSearchSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RunSearchSettings defaultInstance = ((RunSearchSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RunSearchSettings())));
        
        public static RunSearchSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection InputFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InputFiles"]));
            }
            set {
                this["InputFiles"] = value;
            }
        }
    }
}
