//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CometUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProteomeDatabaseFile {
            get {
                return ((string)(this["ProteomeDatabaseFile"]));
            }
            set {
                this["ProteomeDatabaseFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NucleotideReadingFrame {
            get {
                return ((int)(this["NucleotideReadingFrame"]));
            }
            set {
                this["NucleotideReadingFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsProteinDB {
            get {
                return ((bool)(this["IsProteinDB"]));
            }
            set {
                this["IsProteinDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SearchType {
            get {
                return ((int)(this["SearchType"]));
            }
            set {
                this["SearchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DECOY_")]
        public string DecoyPrefix {
            get {
                return ((string)(this["DecoyPrefix"]));
            }
            set {
                this["DecoyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fully-digested")]
        public string EnzymeTermini {
            get {
                return ((string)(this["EnzymeTermini"]));
            }
            set {
                this["EnzymeTermini"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AllowedMissedCleavages {
            get {
                return ((int)(this["AllowedMissedCleavages"]));
            }
            set {
                this["AllowedMissedCleavages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0,No_enzyme,0,-,-</string>
  <string>1,Trypsin,1,KR,P</string>
  <string>2,Trypsin/P,1,KR,-</string>
  <string>3,Lys_C,1,K,P</string>
  <string>4,Lys_N,0,K,-</string>
  <string>5,Arg_C,1,R,P</string>
  <string>6,Asp_N,0,D,-</string>
  <string>7,CNBr,1,M,-</string>
  <string>8,Glu_C,1,DE,P</string>
  <string>9,PepsinA,1,FL,P</string>
  <string>10,Chymotrypsin,1,FWYL,P</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EnzymeInfo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EnzymeInfo"]));
            }
            set {
                this["EnzymeInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SearchEnzymeNumber {
            get {
                return ((int)(this["SearchEnzymeNumber"]));
            }
            set {
                this["SearchEnzymeNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SampleEnzymeNumber {
            get {
                return ((int)(this["SampleEnzymeNumber"]));
            }
            set {
                this["SampleEnzymeNumber"] = value;
            }
        }
    }
}
