<?php include "head.php" ; ?>
<html>
<body>
<?php include "topmenu.php" ; ?>
<?php include "imgbar.php" ; ?>

<div id="page">
   <div id="content_full">
      <div class="post hr">

         <h2>Comet parameter: output_mzidentmlfile</h2>

         <ul>
         <li>Controls whether to output search results in an mzIdentML file.
         <li>Valid values are 0 (do not output) or 1 (output).
         <li>The default value is "1" if this parameter is missing.
         <li>Note, the mzIdentML format has these issues:
          <ul>
           <li>(a) It appears as if the mzIdentML format expects decoy entries to exist in the input FASTA file; at least that seems to be the expectation in the documentation that I've read. Comet's mzIdentML output will report decoy protein references even though they do not exist in the underlying FASTA file. The reported decoy protein, like in the other output formats, is generated by appending the decoy prefix to the protein accession that the decoy peptide was generated from. I have no idea if the mzIdentML format allows for this or not.
           <li>(b) Within the "FragmentTolerance" element, the requirement of fragment "search tolerance plus value" (MS:1001412) and "search tolerance minus value" (MS:1001413) make no sense in the context of spectral correlation matching used in Comet, SEQUEST and other tools that perform the cross-correlation score. A fragment bin value and bin offset are needed to encapsulate the corresponding fragment settings in Comet. Currently 1/2 of the "fragment_bin_offset" value is reported for the search tolerance plus/minus values but this is a sad hack that should not be required.
          </ul>
         </ul>

         <p>Example:
         <br><tt>output_mzidentmlfile = 0</tt>
         <br><tt>output_mzidentmlfile = 1</tt>

      </div>
   </div>
   <div style="clear: both;">&nbsp;</div>
</div>

<?php include "footer.php" ; ?>
</html>
