<meta charset="UTF-8">

<div id="page">
   <div id="content_full">
      <div class="post hr">
         <h1>Comet release 2020.01</h1>
            <ul>
               <b>release 2020.01 rev. 0 (2020.01.0), release date 2020/10/20</b>

               <li>Implemented mzIdentML output via the parameter entry
               "<a href="/parameters/parameters_202001/output_mzidentfile.php">output_mzidentmlfile</i></a>".
               The mzIdentML format does not fully support the reporting of Comet results
               so this is considered preliminary support.  Issues with the mzIdentML format for Comet:
               (a) It appears as if the mzIdentML format expects decoy entries to exist in
               the input FASTA file; at least that appears to be the expectation in the
               documentation that I've read.  Comet's mzIdentML output will report decoy
               protein references even though they do not exist in the underlying FASTA file.
               The reported decoy protein, like in the other output formats, is generated by
               appending the decoy prefix to the protein accession that the decoy peptide was
               generated from.  I have no idea if the mzIdentML format allows for this or not.
               (b) Within the "FragmentTolerance" element, the requirement of fragment
               "search tolerance plus value" (MS:1001412) and
               "search tolerance minus value" (MS:1001413) make no sense in the context of
               spectral correlation matching used in Comet, SEQUEST and other tools
               that perform the cross-correlation score. A fragment bin value
               and bin offset are needed to encapsulate the corresponding fragment settings
               in Comet. Currently 1/2 of the 
               "<a href="/parameters/parameters_202001/fragment_bin_offset.php">fragment_bin_offset</i></a>"
               value is reported for the search tolerance plus/minus values but this is a
               sad hack that should not be required.

               <li>Extended the number of preliminary score ion "bins" considered from 200 to 1000.
               This allows matching many more fragment ions in the preliminary score algorithm
               to get a more representative matched ion count reported in the output files.
               Before this change, the matched fragment numbers are likely under-reported for
               many spectral matches of longer peptides.

               <li>Added the parameter entry
               "<a href="/parameters/parameters_202001/add_Z1_ions.php">add_Z1_ions</i></a>"
               to consider "Z&bull; + 1" ions (typically for ETD/ECD searches).
               Feature requested by A. Grimaud.

               <li>Add support for Comet's internal decoy peptides in the indexed database search
               (intended for real-time search application).
               As decoy peptides don't need to be explicitly present in the indexed database,
               this reduces the index database size and indexing time by nearly half compared
               to indexing a FASTA file composed of target+decoy sequences.

               <li>Add support for reporting all matched proteins in an indexed database search.
               Previously only one protein name was returned for each peptide identification.

               <li>Corrected/changed residue 'O' from Ornithine to Pyrrolysine. This
               entails retiring the
               "<a href="/parameters/parameters_201901/add_O_ornithine.php">add_O_ornithine</i></a>"
               parameter entry and adding 
               "<a href="/parameters/parameters_202001/add_O_pyrrolysine.php">add_O_pyrrolysine</i></a>".
               Thanks to P. Charles for reporting the correction.

               <li>Added support for changing the text file output file extension from its default
               "txt" extension to a custom file extension via a new parameter entry
               "<a href="/parameters/parameters_202001/text_file_extension.php">text_file_extension</i></a>".
               Text file outputs are generated when the
               "<a href="/parameters/parameters_202001/output_txtfile.php">output_txtfile</i></a>"
               parameter is set to "1".
               This custom/hidden parameter will need to be manually added to your params file for use (i.e.
               it is not present in the example params file available for download nor is it written
               in the comet.params.new file generated by the command "comet -p").
               Feature requested by
               <a href="http://www.patternlabforproteomics.org/">PatternLab for Proteomics</a>.

               <li>Added a parameter entry
               "<a href="/parameters/parameters_202001/explicit_deltacn.php">explicit_deltacn</i></a>"
               which controls how the deltaCn output score is calculated.
               By default, Comet will very crudely analyze sequence similarity when calculating
               the deltaCn score. This results in the deltaCn being calculated between the top
               hit and the first dissimilar peptide in order to avoid very small deltaCn values
               when the top N peptides are all the same (such as different modified forms of the
               same peptide).  When 
               "<a href="/parameters/parameters_202001/explicit_deltacn.php">explicit_deltacn</i></a>".
               is set to "1", the sequence similarity analysis is not used and the deltaCn is
               calculated as the difference between the top scoring peptide and the second best
               scoring peptide.
               This custom parameter will need to be manually added to your params file for use.
               Feature requested by
               <a href="http://www.patternlabforproteomics.org/">PatternLab for Proteomics</a>.

               <li>Added "sp_rank" and "retention_time_sec" columns to the text output.
               Feature requested by
               <a href="http://www.patternlabforproteomics.org/">PatternLab for Proteomics</a>.

               <li>Added preliminary support for searching TIMS-TOF mzML files.  MSToolkit updates
               now allow TIMS-TOF mzML files to be searched. Previous parsing of the mzML file
               would return no spectra to search.  I should note that I'm not sure what the
               returned scan numbers represent.  Also, a function to return the file's last
               scan number was not updated for these TIMS-TOF files; this causes
               Comet's search progress percentage reporting to return nonsensical values.
               Thanks to D. Shteynberg and M. Hoopmann for the MSToolkit mods to support this.

               <li>Extend the
               "<a href="/parameters/parameters_202001/activation_method.php">activation_method</i></a>"
               parameter to accept "SID" as a filter string for searching Thermo mzML/mzXML files
               with the string " sid=" in the filter line text. Feature requested by J. Mohr.

               <li>Removed reporting of "deltacnstar" in the pepXML output.  It appears that
               the score has been reported as "0.0" for every result and I've never understood
               what it represented so I'm taking this opportunity to get rid of it now.

               <li>Changed the "No_enzyme" text to "Cut_everywhere" in the enzyme definition
               of the exported comet.params file.  Hopefully this clarifies the purpose
               of that enzyme definition of cleaving everywhere (as opposed to no digestion
               which "No_enzyme" could convey). The enzyme text strings in the params file
               have no function in Comet and can be named anything.

               <li>Bug fix:  When a protein N-terminal static modification is specified, it
               was not being applied in the preliminary score routine for N-terminal peptides
               resulting from a
               <a href="http://comet-ms.sourceforge.net/parameters/parameters_201901/clip_nterm_methionine.php">clipped methionine</a>.
               Thanks to Thermo's BioPharma Finder group for reporting the bug.

               <li>Bug fix:  In the text file output, the position of static C-terminal
               modifications in the "modifications" column was always incorrectly reported
               as "1" in the encoded modfication string; this has been corrected.
               Thanks to Thermo's BioPharma Finder group for reporting the bug.

               <li>Bug fix:  When running multiple searches via interfacing with
               CometWrapper.dll under Windows, the output file of subsequent searches was
               not updating. Thus searches were simply overwriting the first output file.
               This has been addressed with a simple variable initialization.
               Thanks to Thermo's BioPharma Finder group for reporting the bug.

               <li>Bug fix:  Corrected a bug where every matched/duplicate protein was not
               always reported due to a rounding/precision issue with storing of the xcorr.
               This was noticed for an edge case (bad spectrum, small database) that should
               not affect users in practice.

               <li>I've sadly had to push off Comet-PTM integration to the next release again.

            </ul>

            <p>Documentation for parameters for release 2020.01
            <a href="/parameters/parameters_202001/">can be found here</a>.

            <p>Go download from the <a href="https://sourceforge.net/projects/comet-ms/files/">download</a> page.

      </div>
   </div>

   <div style="clear: both;">&nbsp;</div>
</div>
