name: Build on Linux for ubuntu-22.04-arm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: actions/checkout@v4

    - name: Build Comet
      run: make

    - name: Test Comet
      run: ./comet.exe -p

    - name: Prepare Comet release
      run: |
        mkdir release && \
        cp comet.exe release/comet.aarch64.linux.exe && \
        cp README.md release/README.md

    - name: Upload build artifiacts
      uses: actions/upload-artifact@v4
      with:
        name: comet-aarch64-linux
        path: release/*

    - name: Upload binaries to the release
      uses: svenstaro/upload-release-action@v2
      if: ${{ github.event_name == 'release' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: release/*
        overwrite: true
        file_glob: true
